# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#

workflows:
  version: 2

  nightly:
    jobs:
      - update_meetup
    triggers:
      - schedule:
          # Every night at 4am ET
          cron: "0 9 * * *"
          filters:
            branches:
              only: master

  day_before:
    jobs:
      - notify_slack_roles
    triggers:
      - schedule:
          # Every Mon evening at 6pm ET
          cron: "0 22 * * 1"
          filters:
            branches:
              only: master

  pre_hacknight:
    jobs:
      - reset_pitches
    triggers:
      - schedule:
          # Every Tues evening at 6pm ET
          cron: "0 22 * * 2"
          filters:
            branches:
              only: master

  post_hacknight:
    jobs:
      - notify_slack_pitches
      - backup_trello
      - save_pitch_data
    triggers:
      - schedule:
          # Every Wed morning at 4am ET
          cron: "0 8 * * 3"
          filters:
            branches:
              only: master

version: 2

jobs:
  default: &default_job
    docker:
      - image: circleci/python:3.6.2
    # See sample.env file for full details
    environment:
        # Used to ignore cleaning CT101 card from pitch list, but seems better
        # to repopulate list manually each week
      - TRELLO_CARD_IGNORE_LIST: ""
        # For list: "Tonight's Pitches"
      - TRELLO_LIST_TONIGHT: 58e158f29b0ae02ab71b9a87
        # For list: "Recent Pitches (Past Month)"
      - TRELLO_LIST_RECENT: 58e158eba6846a4fb012404c
        # For channel: #general
      - SLACK_ANNOUNCE_CHANNEL_PUB: C04TJ34KG
        # For channel: #organizing-open
      - SLACK_ANNOUNCE_CHANNEL_ORG: C4SHX39B2
      - MAILCHIMP_API_USER: patcon_
      # Testing list for now
      - MAILCHIMP_LIST_ID: 9ad4b62fac
      # See: https://us11.admin.mailchimp.com/templates/design?tid=364745
      - MAILCHIMP_TEMPLATE_ID: 364745
      # Section to replace with project data in template above
      - MAILCHIMP_SECTION_NAME: projects

        # For the following sensitive envvars, check the CircleCI UI.
        #   - GITHUB_ACCESS_TOKEN
        #   - SLACK_API_TOKEN
        #   - TRELLO_APP_KEY
        #   - TRELLO_SECRET
        #   - MAILCHIMP_API_KEY
        #
        # See: https://circleci.com/gh/CivicTechTO/civictechto-scripts/edit#env-vars
    steps:
      - checkout

      - run: &decrypt_files
          name: decrypt files
          command: |
            openssl aes-256-cbc -k "$TRELLO_SECRET" -in service-key.json.enc -out service-key.json -d

      - restore_cache: &restore_cache
          keys:
          - v1-dependencies-{{ checksum "requirements.txt" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: &install_dependencies
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            # When fetching package from new git repo, use (w)ipe action
            pip install -r requirements.txt --exists-action w

      - save_cache: &save_cache
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}

  reset_pitches:
    <<: *default_job
    steps:
      - checkout
      - run: {<<: *decrypt_files}
      - restore_cache: {<<: *restore_cache}
      - run: {<<: *install_dependencies}
      - save_cache: {<<: *save_cache}
      - run:
          name: run script
          command: |
            . venv/bin/activate
            python3 clean_pitch_list.py

  backup_trello:
    <<: *default_job
    steps:
      - checkout
      - run: {<<: *decrypt_files}
      - restore_cache: {<<: *restore_cache}
      - run: {<<: *install_dependencies}
      - save_cache: {<<: *save_cache}
      - run:
          name: run script
          command: |
            . venv/bin/activate
            #python3 backup_trello.py

  save_pitch_data:
    <<: *default_job
    steps:
      - checkout
      - run: {<<: *decrypt_files}
      - restore_cache: {<<: *restore_cache}
      - run: {<<: *install_dependencies}
      - save_cache: {<<: *save_cache}
      - run:
          name: run script
          command: |
            . venv/bin/activate
            python3 update_pitch_csv.py

  notify_slack_pitches:
    <<: *default_job
    steps:
      - checkout
      - run: {<<: *decrypt_files}
      - restore_cache: {<<: *restore_cache}
      - run: {<<: *install_dependencies}
      - save_cache: {<<: *save_cache}
      - run:
          name: run script
          command: |
            . venv/bin/activate
            python3 notify_slack_pitches.py

  notify_slack_roles:
    <<: *default_job
    steps:
      - checkout
      - run: {<<: *decrypt_files}
      - restore_cache: {<<: *restore_cache}
      - run: {<<: *install_dependencies}
      - save_cache: {<<: *save_cache}
      - run:
          name: run script
          command: |
            . venv/bin/activate
            python3 notify_slack_roles.py

  update_meetup:
    <<: *default_job
    steps:
      - checkout
      - run: {<<: *decrypt_files}
      - restore_cache: {<<: *restore_cache}
      - run: {<<: *install_dependencies}
      - save_cache: {<<: *save_cache}
      - run:
          name: run script
          # Meetup key set as envvar CTTO_MEETUP_API_KEY
          command: |
            . venv/bin/activate
            python3 gsheet2meetup.py --yes \
              --meetup-group-slug "Civic-Tech-Toronto" \
              --gsheet-url "https://docs.google.com/spreadsheets/d/19B5sk8zq_pYZVe0DMGCKKBP2jYolm6COfJfIq45vwCg/edit#gid=2098195688"

  # Doesn't yet run in workflow
  email_monthly_update:
    <<: *default_job
    steps:
      - checkout
      - run: {<<: *decrypt_files}
      - restore_cache: {<<: *restore_cache}
      - run: {<<: *install_dependencies}
      - save_cache: {<<: *save_cache}
      - run:
          name: run script
          command: |
            . venv/bin/activate
            python3 send_monthly_project_email.py
