name: Nightly

on:
  schedule:
    # Every night at 4am ET
    # See: https://crontab.guru/#0_9_*_*_*
    - cron: '0 9 * * *'
  repository_dispatch:
    types: [force-nightly]
  workflow_dispatch:

jobs:
  noop:
    runs-on: ubuntu-latest
    steps:
      - run: echo This workflow is just a placeholder to trigger others...
