name: Post-Hacknight

on:
  schedule:
    # Every Wednesday morning at 4am ET (08:00 UTC)
    # See: https://crontab.guru/#0_8_*_*_3
    - cron: '0 8 * * 3'
  repository_dispatch:
    types: [force-post-hacknight]

jobs:
  noop:
    runs-on: ubuntu-latest
    steps:
      - run: echo This workflow is just a placeholder to trigger others...
